<?php

namespace app\components;

class View extends \yii\web\View
{
    function render($view, $params = [], $context = null)
    {
        return str_ireplace('ipsum', 'text', parent::render($view, $params, $context)); // TODO: Change the autogenerated stub
    }
}